import { library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import {
  faCircleQuestion,
  faHourglassHalf,
  faHeadset,
  faLayerGroup,
  faBrain,
  faPaperPlane,
  faCheckCircle,
  faCopy,
  faPlus,
  faPrint,
  faExclamationCircle,
  faMagic,
  faRobot,
  faRefresh,
  faTimes,
  faImage,
  faCloudUploadAlt,
  faMapMarkerAlt,
  faFileImage,
  faInfoCircle,
  faWandMagicSparkles,
  faSyncAlt,
  faHandPointer,
  faCheck,
  faLightbulb,
  faPhone,
  faClock,
  faQuestionCircle,
  faExclamationTriangle,
  faTimesCircle,
  faBuilding,
  faSpinner,
  faStar,
  faTag,
  faList,
  faKey,
  faChevronRight
} from '@fortawesome/free-solid-svg-icons';

// Agregar los iconos a la librería
library.add(
  faCircleQuestion,
  faHourglassHalf,
  faHeadset,
  faLayerGroup,
  faBrain,
  faPaperPlane,
  faCheckCircle,
  faCopy,
  faPlus,
  faPrint,
  faExclamationCircle,
  faMagic,
  faRobot,
  faRefresh,
  faTimes,
  faImage,
  faCloudUploadAlt,
  faMapMarkerAlt,
  faFileImage,
  faInfoCircle,
  faWandMagicSparkles,
  faSyncAlt,
  faHandPointer,
  faCheck,
  faLightbulb,
  faPhone,
  faClock,
  faQuestionCircle,
  faExclamationTriangle,
  faTimesCircle,
  faBuilding,
  faSpinner,
  faStar,
  faTag,
  faList,
  faKey,
  faChevronRight
);

export { FontAwesomeIcon };
